'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0"),
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()), MySettings)

#Region "Fonctionnalité Enregistrement automatique My.Settings"
#If _MYTYPE = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region

        Public Shared ReadOnly Property [Default]() As MySettings
            Get

#If _MYTYPE = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("EyeChat")>
        Public Property UserName() As String
            Get
                Return CType(Me("UserName"), String)
            End Get
            Set
                Me("UserName") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property UniqueId() As String
            Get
                Return CType(Me("UniqueId"), String)
            End Get
            Set
                Me("UniqueId") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("0")>
        Public Property Id() As Integer
            Get
                Return CType(Me("Id"), Integer)
            End Get
            Set
                Me("Id") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property RoomDisplay() As Boolean
            Get
                Return CType(Me("RoomDisplay"), Boolean)
            End Get
            Set
                Me("RoomDisplay") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("Collapsed")>
        Public Property RoomDisplayStr() As String
            Get
                Return CType(Me("RoomDisplayStr"), String)
            End Get
            Set
                Me("RoomDisplayStr") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property RoomDisplayInverted() As Boolean
            Get
                Return CType(Me("RoomDisplayInverted"), Boolean)
            End Get
            Set
                Me("RoomDisplayInverted") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("10")>
        Public Property SizeDisplayUsers() As Integer
            Get
                Return CType(Me("SizeDisplayUsers"), Integer)
            End Get
            Set
                Me("SizeDisplayUsers") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("Collapsed")>
        Public Property RoomNameDisplayUsers() As Global.System.Windows.Visibility
            Get
                Return CType(Me("RoomNameDisplayUsers"), Global.System.Windows.Visibility)
            End Get
            Set
                Me("RoomNameDisplayUsers") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("Collapsed")>
        Public Property NameRoomDisplayUsers() As Global.System.Windows.Visibility
            Get
                Return CType(Me("NameRoomDisplayUsers"), Global.System.Windows.Visibility)
            End Get
            Set
                Me("NameRoomDisplayUsers") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("Visible")>
        Public Property NameDisplayUsers() As Global.System.Windows.Visibility
            Get
                Return CType(Me("NameDisplayUsers"), Global.System.Windows.Visibility)
            End Get
            Set
                Me("NameDisplayUsers") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("A")>
        Public Property AppNameDisplay() As String
            Get
                Return CType(Me("AppNameDisplay"), String)
            End Get
            Set
                Me("AppNameDisplay") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property ComputerName() As String
            Get
                Return CType(Me("ComputerName"), String)
            End Get
            Set
                Me("ComputerName") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property WindowsName() As String
            Get
                Return CType(Me("WindowsName"), String)
            End Get
            Set
                Me("WindowsName") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property PlanningMode() As Boolean
            Get
                Return CType(Me("PlanningMode"), Boolean)
            End Get
            Set
                Me("PlanningMode") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property PlanningMode2() As Boolean
            Get
                Return CType(Me("PlanningMode2"), Boolean)
            End Get
            Set
                Me("PlanningMode2") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("Benoit")>
        Public Property PlanningName2() As String
            Get
                Return CType(Me("PlanningName2"), String)
            End Get
            Set
                Me("PlanningName2") = Value
            End Set
        End Property
    End Class
End Namespace

Namespace My

    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Module MySettingsProperty

        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>
        Friend ReadOnly Property Settings() As Global.EyeChat.My.MySettings
            Get
                Return Global.EyeChat.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
